import './globals.css'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({ 
  weight: ['400',"500","600","700","800"],
  subsets: ['latin'] 
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={montserrat.className}>
      <body className='w-full h-screen'>{children}</body>
    </html>
  )
}
